<a href="https://colab.research.google.com/github/gustmdtmd/pythondemo/blob/main/python_11_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy
 - Numpy는 Numerical Python의 줄임말로, 파이썬에서 산술계산을 위한 가장 필수 패키지 중 하나이다.
 - 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통언어처럼 사용한다.
 - 반복문을 작성할 필요없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
 - 배열 데이터르 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
 - 선형대수, 난수 생성기등에 사용된다.
 - C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.
   
공식문서 https://numpy.org/doc/stable/   
numpy 100문제 https://github.com/rougier/numpy-100

### 1. 데이터 생성

In [9]:
#!pip install numpy
import numpy as np

In [3]:
a = np.zeros(3)  # 1차원 배열 = 벡터
a

array([0., 0., 0.])

In [4]:
print(a)

[0. 0. 0.]


In [6]:
# 처음 객체들은 type(). dir()을 해본다.
print(type(a))
print(dir(a))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [8]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
a

array([1, 2, 3])

In [17]:
print(type(a))
print(dir(a))
print(len(dir(a)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [10]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [16]:
print(type(b))
print(dir(b))
print(len(dir(b)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [12]:
# 3차원 배열 이상 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
print(type(c))
print(dir(c))
print(len(dir(c)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [20]:
# 배열은 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 이다.
a = np.array([1,'2',3])
print(a)
print(type(a))
print(type(a[0]))

['1' '2' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [23]:
# boolean값이 있어도 문자열이 있다면 전체가 문자로 바뀐다.
b = np.array(['a', 1, True])
print(b)
print(type(b))
b

['a' '1' 'True']
<class 'numpy.ndarray'>


array(['a', '1', 'True'], dtype='<U21')

In [25]:
# 배열에서 True = 1, False = 0으로 출력된다.
c = np.array([1, True, 2, False])
print(c)
print(type(c))
c
print(type(c[0]))

[1 1 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


### np.zeros
- tuple로 인자를 넣으면 그대로 모양을 만든다.
- (2, 3) : 2행 3열 행렬을 만든다.
- zeros는 기본값으로 0.으로 값을 모두 채운다.   
  a = np.zeros((2,3))   
  a = np.zeros([2,3])

In [26]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
c = np.zeros([2,3,2])
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

### np.eye
- eye는 단위 행렬
- 숫자만 사용할 수 있다.

In [28]:
# 인자값이 1개이면 행과 열이 같다.
# 3행 3열이 만들어진다. 
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# eye은 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬 생성
b = np.eye(3,2)
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [37]:
# 크기(1)가 시작되는 위치를 지정할 수 있다.
c = np.eye(3, 4, k=1)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identity
- 수학에서 단위행렬은 영어로 identity matrix
- 크기 한개만 지정해서 생성할 수 있다.

In [39]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# TypeError
# 인자 하나만 지정할 수 있다.
b = np.identity(3,2)
b

TypeError: ignored

### np.full
- 지정한 크기의 배열을 생성하고 채울 값을 지정한다.
- 2행 2열의 배열 생성 후 1로 채워준다.   
  np.full((2,2),1)

In [42]:
# 2행 2열의 배열을 생성하고 1로 초기화 해준다.
a = np.full((2,2), 1)
a

array([[1, 1],
       [1, 1]])

In [44]:
# 1행 3열의 배열을 생성하고 4로 채워준다.
b = np.full(3,4)
b

array([4, 4, 4])

In [46]:
# 2행 2열의 배열을 생성하고 [1,2]로 각 행을 지정해준다.
c = np.full((2,2),[1,2])
c

array([[1, 2],
       [1, 2]])

In [47]:
# 2행 2열의 배열을 생성하고 [1,2],[3,4]로 순서대로 행을 채워준다.
d = np.full((2,2),[[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [48]:
# 각 행에 메모리에 남아있는 찌꺼기 값이 들어간다. 매번 바뀐다.
a = np.empty(3)
a

array([3.48154069e-316, 6.79038653e-313, 5.43472210e-322])

In [50]:
k = np.zeros((2,3))
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# zeros에서 생성한 배열이 있으면 배열의 값을 0으로 채워준다.
b = np.empty((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
c = np.empty((2,5))
c

array([[3.45223904e-316, 1.77863633e-322, 0.00000000e+000,
        0.00000000e+000, 2.41907520e-312],
       [1.15455919e-071, 7.61456000e+169, 7.78936012e-091,
        4.91528562e-062, 8.14081864e-315]])

### np.ones
- 배열의 모든 값을 1로 채워준다.

In [54]:
# 1행 3열의 배열이 생성되고 모든 값을 1로 채운다.
a = np.ones(3)
a

array([1., 1., 1.])

In [56]:
#b = np.ones((2,3))
b = np.ones([2,3])
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
c = np.empty((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
e = np.eye(3,4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [61]:
d = np.empty((3,4))
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [62]:
# 값을 지정해주면 empty로 출력시 값이 따라가지않는다.
e = np.full((3,4),0)
e

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [65]:
f = np.empty((3,4))
f

array([[3.40727274e-316, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.74084271e+169, 7.11579326e-091,
        1.20009338e-071],
       [9.98705796e-048, 1.57144795e-076, 3.99910963e+252,
        1.46030983e-319]])

### _like
- _like가 붙으면 shape가 같게 만들어진다.
- 연산하기 위해서 shape을 맞춰야하는 경우가 있다.

In [68]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a.shape

(2, 3)

In [70]:
# 배열(행렬)은 같게 가져오지만 값은 다르게 가져온다.
b = np.empty_like(a)
b

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [71]:
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [72]:
c.shape

(2, 2)

In [74]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
d.shape

(3, 3)

In [76]:
# ValueError
c + b

ValueError: ignored

### linspace
- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세번째 num인자값이 생략되어 있으므로 start와 end 계산해서 default 50이 생성된다.  
  linspace(start, end, num)   
  linspace(0, 49)   #num = 50

In [78]:
a = np.linspace(0,49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [79]:
# 3번째(num) 값을 지정하지 않으면 default값이 50이기때문에 알아서 값을 나누어 출력한다.
b = np.linspace(1, 5)
b

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [80]:
len(b)

50

In [81]:
# 1부터 10까지 3개의 요소를 생성한다.
# 기본은 endpoint = True 로 설정되어 있기 때문에 10이 포함된다.
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [82]:
# 1부터 10미만 사이에서 3개의 요소를 생성한다.
# endpoint = False로 설정되어 있으므로 10은 포함이 안된다.
np.linspace(1, 10, 3, endpoint=False)

array([1., 4., 7.])

### logspace
- linspace와 비슷하다.
- log scale을 사용하는 차이가 있다.
- 1부터 50까지 사이의 10개의 요소를 생성한다.
     np.logspace(1, 50, 10) 

In [83]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### *dtype*
-numpy는 c언어를 기반으로 해서 만들었기 때문에 c의 데이터 타입을 차용할 수 있다.

In [84]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [86]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [88]:
b = np.array([1,2,3], dtype=np.int8)
b

array([1, 2, 3], dtype=int8)

In [89]:
# np.int8은 -128 ~ 127 사이의 값을 저장할 수 있다.
c = np.array([-127, -128, 17, 2, 3, -127, -128, -127], dtype=np.int8)
c

array([-127, -128,   17,    2,    3, -127, -128, -127], dtype=int8)

In [91]:
# int는 python의 int를 사용한다.
d = np.array([127, 2, 3, -127, -128], dtype=int)
d

array([ 127,    2,    3, -127, -128])

In [92]:
type(d[0])

numpy.int64

### python 도움말

In [93]:
# ? 도움말 
?sum

In [94]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



### numpy 도움말

In [95]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.Bytes0.sum
    Scalar method identical to the corresponding array attribute.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.Bytes0.cumsum
    Scal

In [96]:
a = np.array([[1,2,3],[4,5,6]])
# 배열의 형태를 알려준다.
a.shape  

(2, 3)

In [97]:
# 배열이 몇 차원인지 알려준다.
# shape로도 알 수 있다.
a.ndim

2

In [99]:
# 데이터 타입을 알려준다.
# numpy 처리법 int64 = 8바이트
a.dtype

dtype('int64')

In [101]:
# 요소의 개수
# shape로도 알 수 있다.
a.size

6

In [102]:
# 요소당 byte수를 알려준다.
a.itemsize

8

### 2. numpy와 python의 속도 차이

In [103]:
# ranger
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

값이 작을 때는 속도가 비슷하다.  
값이 커지면 속도 차이가 난다. (빠름 : numpy > python)

In [105]:
# numpy을 이용한 계산
%time np.sum(np.arange(1000000000))

CPU times: user 1.59 s, sys: 2.55 s, total: 4.14 s
Wall time: 4.14 s


499999999500000000

In [106]:
# python을 이용한 계산
%time sum(range(1000000000))

CPU times: user 22.6 s, sys: 0 ns, total: 22.6 s
Wall time: 22.7 s


499999999500000000

같은 np.sum() 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.

In [10]:
%time np.sum(np.arange(1000000000))

CPU times: user 1.8 s, sys: 1.56 s, total: 3.36 s
Wall time: 3.39 s


499999999500000000

In [ ]:
%time np.sum(range(1000000000))

### 3. copy
※ 대입문 6가지
a = 1   
a = b = 1   
a,b = 1, 2   
a, *b = 1, 2, 3   
a += 1   
global, nonlocal

#### python에서 copy

In [11]:
a = [1, 2, 3]  # heterogeneousm sequence, mutable

In [12]:
b = a

In [13]:
b

[1, 2, 3]

In [14]:
a is b # 메모리 주소값 비교

True

In [15]:
# a와 b가 메모리 주소를 공유
# b의 값을 변경하면 a의 값도 변경된다.
b[0] = 7

In [16]:
b

[7, 2, 3]

In [17]:
a

[7, 2, 3]

list copy

In [18]:
a = [1, 2, 3]

In [19]:
# copy()는 똑같은 값만 가지고 메모리는 공유하지 않는다.
b = a.copy()

In [21]:
# 메모리 주소 비교
a is b

False

In [22]:
# 메모리 확인 id()
id(a)

140068860214784

In [23]:
id(b)

140068859543424

In [24]:
# 값을 비교
a == b

True

In [27]:
b[0] = 8
# a는 변경되지 않는다. 메모리 주소가 다르기때문.
print(a)
print(b)

[1, 2, 3]
[8, 2, 3]


In [28]:
print(a is b)
print(a == b)

False
False


list가 2차원일 때

In [29]:
a = [[1,2,3]]

In [30]:
type(a)

list

In [31]:
# shallow copy(얇은복사)
b = a.copy()

In [32]:
print(a is b)
print(a == b)

False
True


In [34]:
print(a[0] is b[0])
print(a[0] == b[0])

True
True


list deep copy

In [35]:
import copy

In [36]:
a = [[1,2,3]]
b = copy.deepcopy(a)

In [37]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [40]:
print(a is b)
print(a == b)
print(a[0] is b[0]) # deep coyp가 됨
print(a[0] == b[0])

False
True
False
True


[:]는 전체라는 뜻이다.   
슬라이싱 방식으로 1차 리스트일 때는 재할당하면 deepcopy가 발생된다. 슬라이싱 2차 리스트 이상인 경우 shallow copy가 발생한다.

In [42]:
a = [1,2,3]
b = a[:]
print(a is b)
print(a == b)
b[0] = 7
print(a is b)
print(a == b)

False
True
False
False


In [43]:
a = [[1,2,3]]
# 슬라이싱 2차 이상인 경우 shallow copy가 된다.
b = a[:]
print(a is b)
print(a == b)
b[0][0] = 7
print(a is b)
print(a == b)

False
True
False
True


※ python의 copy는 기본적으로 shallow copy를 한다.

#### numpy의 copy

In [44]:
a = b = np.array([1,2,3])

In [46]:
print(a is b)
print(a == b)

True
[ True  True  True]


array는 sequence타입으로 인덱싱과 슬라이싱이 가능하다.

In [47]:
a[0] # indexing

1

In [48]:
a[:] # slicing

array([1, 2, 3])

In [50]:
# array는 mutable 이다.
# 예외가 몇 가지 있지만 mutable에 가깝다.
a[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


array은 homogeneous, sequence, mutable이다.

array deepcopy

In [52]:
a = np.array([[1,2,3]])
# numpy는 기본적으로 deepcopy이다.
b = a.copy()

In [54]:
print(a is b)

False


In [55]:
print(a[0] is b[0])

False


### 4. as 계열
다른 데이터 타입을 가져와서 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.

In [59]:
# python의 list데이터 타입을 int ndarry로 변환
a = [1, 2, 3] # python의 list
print(type(a))
print(type(a[0]))
b = np.array(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [61]:
# python의 list데이터 타입을 int ndarry로 변환 (asarray())
a = [1, 2, 3] # python의 list
print(type(a))
print(type(a[0]))
b = np.asarray(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [63]:
# python의 list데이터 타입을 float ndarry로 변환 (asfarray())
a = [1, 2, 3] # python의 list
print(type(a))
print(type(a[0]))
b = np.asfarray(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [65]:
# python의 list데이터 타입 float이면 float ndarray로 변환
# python의 list데이터 타입 int이면 int ndarray로 변환
# 같은 타입으로 변환할 땐 asarray() 혹은 array()를 사용해도 된다.
a = [1., 2., 3.]
print(type(a))
print(type(a[0]))

b = np.asarray(a)
print(type(b))
print(type(b[0]))

c = np.array(a)
print(type(c))
print(type(c[0]))

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


### 5. 값 가져오기

####(1) comma로 값 가져오기

In [66]:
a = [[1, 2, 3], [4, 5, 6]] #python
b = np.array([[1, 2, 3], [4, 5, 6]]) #numpy

In [67]:
# 1차원 리스트로 가져온다.
a[0]

[1, 2, 3]

In [71]:
# TypeError
# 인덱싱에서는 , 를 사용할 수 없다.
a[0,1]

TypeError: ignored

슬라이싱 함수를 이용해서 comma를 사용하는 방법은 가능하다.

In [72]:
# 2차원 리스트로 가져온다.
a[slice(0,1)] # 0번째 행부터 1행 미만의 데이터를 가져온다.

[[1, 2, 3]]

In [74]:
a[slice(0,2)] # 0번째 행부터 2행 미만의 데이터를 가져온다.

[[1, 2, 3], [4, 5, 6]]

In [76]:
a[0:2]

[[1, 2, 3], [4, 5, 6]]

numpy는 기본적으로 인덱싱/슬라이싱할 때 comma를 사용할 수 있다.

In [78]:
# numpy
# b[행, 열]
print(b[0,2]) # 인덱싱
print(b[0,-1]) # -1은 행의 마지막 열을 가져온다.

3
3


In [79]:
# python
# a[행][열]
print(a[0][2])
print(a[0][-1])

3
3


#### (2) boolean indexing

In [80]:
a = [[1,2,3,4]] # python list

In [81]:
# TypeError
a > 3

TypeError: ignored

In [82]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

array를 scalar와 연산하면 elementwise로 계산한다.   
(elementwise : 원소별로 각각 계산이 된다.)

In [84]:
# 원소별로 비교해서 True/False로 계산한다.
#1>2, 2>2, 3>2, 4>2
# numpy에서는 가능하고 python에서는 안된다.
b>2   # array > scalar

array([False, False,  True,  True])

numpy는 indexing, slicing 자리에 조건도 쓸 수 있다.  
True에 해당되는 값만 가져온다.

In [85]:
# boolean indexing
b[np.array([False, False, True, True])] # b[1,2,3,4] True에 해당하는 값만 가져온다.

array([3, 4])

In [86]:
b[b>2]

array([3, 4])

numpy에서 booleaning indexing 조건  
- array만 가능하다.
- numpy True, False로만 가능하다.
- shape이 맞아야 한다. (개수가 맞을 때만 사용할 수 있다.)

In [87]:
# python에서는 지원 안한다.
a = [1,2,3,4]
a[True,True,False,False]

TypeError: ignored

### (3) fancy indexing

In [93]:
b = np.arange(100).reshape(20,5) # reshape(행, 열) 배열의 구조 변경
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

인덱싱, 슬라이싱 자리에 괄호를 하나 더 넣으면 fancy indexing 할 수 있다.  
여러개를 한번에 인덱싱할 수 있다.

In [102]:
b[:] # 전체를 가져온다. b[:,:]와 같다.
# b[행, 열]
print(b[1:3]) # 1행부터 3행 미만의 데이터를 가져온다.
print(b[1:3,2:4]) # 1행부터 3행 미만이면서 2열부터 4열 미만의 데이터를 가져온다.
print(b[[1,3,5]]) # b[[1,3,5], :] 1행, 3행 ,5행의 데이터를 가져온다. []괄호 추가 (fancy indexing)
print(b[[1,3,5],[0,2,4]]) # 1행 0열, 3행 2열, 5행 4열의 데이터를 가져온다.

[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 7  8]
 [12 13]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[ 5 17 29]


fancying indexting은 인덱싱 기법만 사용할 수 있다.  
":"(클론)은 슬라이싱 기법이므로 지원하지 않는다.

In [103]:
# SyntaxError
b[[2:5]]

SyntaxError: ignored

In [104]:
# 0열, 2열, 4열에 해당하는 모든 행을 가져온다.
b[:,[0,2,4]]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39],
       [40, 42, 44],
       [45, 47, 49],
       [50, 52, 54],
       [55, 57, 59],
       [60, 62, 64],
       [65, 67, 69],
       [70, 72, 74],
       [75, 77, 79],
       [80, 82, 84],
       [85, 87, 89],
       [90, 92, 94],
       [95, 97, 99]])

In [106]:
# 개수가 같게 지정되야 한다. 행과 열의 개수
b[[1,3,4],[0,2,1]] # 정상처리
b[[1,3,4],[0,2]] # IndexError

IndexError: ignored