<a href="https://colab.research.google.com/github/gustmdtmd/pythondemo/blob/main/python_19_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

구글드라이브 연결



In [12]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/python_demo

Mounted at /content/drive
/content/drive/MyDrive/python_demo


In [1]:
import numpy as np
import pandas as pd

### 버전 확인

In [5]:
# python
import sys
print(sys.version)

!python --version

3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0]
Python 3.8.16


In [7]:
# numpy
np.__version__

'1.21.6'

In [10]:
#pandas
pd.__version__

'1.3.5'

In [ ]:
# 구글 colab
!pip freeze

numpy datatype : ndarry, matrix  
pandas datatype : Series, DataFrame(2차원)

### 파일 형식 데이터 불러오기

In [15]:
# 읽어오는 파일에 컬럼명이 없으면 header=None을 설정한다.
# 그렇지 않으면 첫번째 줄을 컬럼명으로 인식을 하기 때문이다.
# header파라미터의 default:'infer'
data = pd.read_csv('pdsample/num.txt', header=None)
data

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [17]:
type(data)

pandas.core.frame.DataFrame

In [38]:
# 컬럼(열) - pandas에서는 열의 인덱스가 0인 값들을 가져온다.
print(data[0])
print(type(data[0])) # Series

0    1
1    6
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [36]:
# index(행) iloc = index loc
print(data.iloc[0])
print(type(data.iloc[0]))  # Series

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [29]:
# numpy 참고
a = np.arange(12).reshape(3,4)
print(a)
print(a[1][2])
print(a[1])
print(a[1,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]
[6 7]


In [31]:
# python list 참고
b = [[ 0,  1,  2,  3]
 ,[ 4,  5,  6,  7]
 ,[ 8,  9, 10, 11]]
print(b[1][2])
print(b[1])
#print(b[1, 2:]) # list에서는 슬라이싱 안됨.

6
[4, 5, 6, 7]


In [41]:
# .values로 가져오면 numpy 포맷으로 변환한다. (배열로 가져온다.)
# 내부적으로 numpy로 되어 있기 때문에 가능하다.
print(data.values)
print(type(data.values))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [ ]:
# __array__ 가 있으면 numpy와 호환된다.
dir(data)

### 웹 주소에서 데이터 불러오기

In [46]:
# header는 기본이 첫 줄울 컬럼명으로 가져오도록 설정이 되어 있기때문에 header='infer' 생략 가능하다. 
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv', header='infer')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [48]:
# 전반적인 데이터 정보 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [49]:
# 기본적으로 앞의 5개를 보여준다.
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [50]:
# 마지막 5개를 보여준다.
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [54]:
# random으로 1개씩 보여준다.
data.sample()

total_bill   tip   sex smoker  day    time  size
170       50.81  10.0  Male    Yes  Sat  Dinner     3

In [58]:
# .head, .tail, .sample 모두 보여줄 개수를 지정할 수 있다.
#data.head(10)
#data.tail(10)
data.sample(10)

total_bill   tip     sex smoker   day    time  size
139       13.16  2.75  Female     No  Thur   Lunch     2
135        8.51  1.25  Female     No  Thur   Lunch     2
215       12.90  1.10  Female    Yes   Sat  Dinner     2
202       13.00  2.00  Female    Yes  Thur   Lunch     2
4         24.59  3.61  Female     No   Sun  Dinner     4
19        20.65  3.35    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
36        16.31  2.00    Male     No   Sat  Dinner     3
66        16.45  2.47  Female     No   Sat  Dinner     2
156       48.17  5.00    Male     No   Sun  Dinner     6

In [60]:
# 데이터만 가져온다.
data.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [62]:
# 행에 대한 인덱스를 가져온다.
data.index

RangeIndex(start=0, stop=244, step=1)

In [63]:
# 컬러명을 가져온다.
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [67]:
# dict 타입
dictdata = {'name' : '홍길동', 'age' : '30'}
#dictdata.name
dictdata['name']

'홍길동'

In [70]:
dir(dict)
dict.items

<method 'items' of 'dict' objects>

In [76]:
# pandas는 dictionary와 attribute 방식 모두 가져올 수 있다.
# dictionary 방식 이용
data['tip']
data['tip'][2]  # tip에 있는 2번째 인덱스 - n열에 있는 m행

3.5

In [80]:
# attribute 방식 이용
data.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [87]:
# KeyError 
# 컬럼을 pancy indexing을 이용해서 가져올 때 index를 이용해서 가져올 수 없다.
#data[[0,2]]

# data['tip', 'day'] 오류.
# pancy indexing. 여러 컬럼을 가져올 때 컬러명으로 가져와야 한다.
data[['tip', 'day']]

tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [90]:
# TypeError 발생
# 컬럼을 컬럼며으로slicing을 이용해서 가져올 수 없다.
# data['tip':'day']

# 행을 slicing을 이용해서 가져올 때는 index를 이용해서 가져올 수 있다.
data[1:3]

total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3

In [94]:
# KeyError
# data[3]
data.iloc[3] # indexing

total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object

하나의 컬럼 또는 행 가져올면 Series로 리턴한다.  
fancy indexing을 이용해서 하나의 컬럼 또는 행을 가져오면 DataFrame으로 리턴한다.

In [96]:
type(data.iloc[3])

pandas.core.series.Series

In [99]:
type(data['tip'])  # Series
type(data.tip)  # Series

pandas.core.series.Series

In [101]:
type(data[['tip']])  # DataFrame. fancy indexiong을 이용하면 원래의 데이터타입으로 반환한다.

pandas.core.frame.DataFrame

In [105]:
data.iloc[0:5]
data.iloc[0:5, :]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [106]:
# iloc가 들어가면 행을 가져온다.
data.iloc[[0, 3, 5]] #fancy indexing  열 = data[['tip','somker','day]]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
3       23.68  3.31    Male     No  Sun  Dinner     2
5       25.29  4.71    Male     No  Sun  Dinner     4

In [108]:
# 3행 1열 
data.iloc[3][1]   # list : a[3][1]  # array : a[3,1]

3.31

In [112]:
# 행과 열 모두 silcing을 사용할 수 있다.
data.iloc[0:3, 1:4]

tip     sex smoker
0  1.01  Female     No
1  1.66    Male     No
2  3.50    Male     No

In [114]:
data.iloc[[0,3,5],[1,4,5]]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

iloc는 indexer을 이용해서 가져오고, loc를 이름(컬러명)을 이용해서 가져온다.

In [116]:
# 행은 이름이 설정되어 있지 않아서 자동으로 생성된 Range index가 이름이 된다.
data.loc[0,'tip']

1.01

In [118]:
# loc도 slicing이 가능하다.
data.loc[0:5, 'tip':'time']

tip     sex smoker  day    time
0  1.01  Female     No  Sun  Dinner
1  1.66    Male     No  Sun  Dinner
2  3.50    Male     No  Sun  Dinner
3  3.31    Male     No  Sun  Dinner
4  3.61  Female     No  Sun  Dinner
5  4.71    Male     No  Sun  Dinner

In [120]:
# loc도 pancy indexing이 가능하다.
data.loc[[0,3,5],['tip','day','time']]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

### at
이름을 한 위치의 값만 가져온다.

In [125]:
data.at[0,'tip'] 
#data.loc[0, 'tip']
#data.iloc[0, 1]

1.01

In [128]:
# at은 slicing 사용을 할 수 없다.
#data.at[0:3, 'tip']

In [130]:
# at은 pancy indexing 사용을 할 수 없다.
data.at[[1,3,5],['tip','smoker','day']]

TypeError: ignored

### iat
iat은 인덱스 번호로 한 위치의 값을 가져온다.

In [134]:
data.iat[0,1]
#data.at[0,'tip']

1.01

In [137]:
# iat은 slicing 사용을 할 수 없다.
data.iat[0:3, 1]

ValueError: ignored

In [139]:
# iat은 pancy indexing 사용을 할 수 없다.
data.iat[[0,3,5],['tip','smoker','day']]

ValueError: ignored

### Boolean indexing

In [143]:
#data.tip >= 5
data['tip'] >= 5

0      False
1      False
2      False
3      False
4      False
       ...  
239     True
240    False
241    False
242    False
243    False
Name: tip, Length: 244, dtype: bool

In [144]:
# True 인것만 가져온다.
data[data['tip'] >= 5]  # data[True, False, True, False...]

total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
73        25.28   5.00  Female    Yes   Sat  Dinner     2
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
185       20.69   5.00    Male     No   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [154]:
data.tip
data['tip']
# True인 값들의 모든 컬럼들을 가져온다.
#a = data[data['tip']>=5] 
# 그 중 tip만 가져온다.
#a['tip']

# 위에 두 식을 하나의 식으로 나타냄.
data[data['tip']>=5]['tip']  # data[data['tip']>=5]의 결과는 DataFrame
#data['tip'][3]  # data['tip']의 결과는 Series

3.31

In [165]:
data[data['tip']>=5].loc[:,'tip':'day']
data[data['tip']>=5].iloc[:,1:5]
a = data[data['sex']== 'Male']
a[data['tip']>=5].iloc[:, 1:5]

<ipython-input-165-ad0cb18b612a>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  a[data['tip']>=5].iloc[:, 1:5]


tip   sex smoker   day
23    7.58  Male     No   Sat
39    5.00  Male     No   Sat
44    5.60  Male     No   Sun
46    5.00  Male     No   Sun
47    6.00  Male     No   Sun
59    6.73  Male     No   Sat
83    5.00  Male    Yes  Thur
88    5.85  Male     No  Thur
116   5.07  Male     No   Sun
141   6.70  Male     No  Thur
142   5.00  Male     No  Thur
156   5.00  Male     No   Sun
170  10.00  Male    Yes   Sat
172   5.15  Male    Yes   Sun
181   5.65  Male    Yes   Sun
183   6.50  Male    Yes   Sun
185   5.00  Male     No   Sun
211   5.16  Male    Yes   Sat
212   9.00  Male     No   Sat
239   5.92  Male     No   Sat

요일이 'Sun'이거나 'Sat'의 tip과 day의 값의 가져오기

In [187]:
data[(data['day'] == 'Sun') | (data['day'] == 'Sat')][['tip','day']]
a = data[(data['day'] == 'Sun') | (data['day'] == 'Sat')]
a['day'].unique()
a[['tip','day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
238  4.67  Sat
239  5.92  Sat
240  2.00  Sat
241  2.00  Sat
242  1.75  Sat

[163 rows x 2 columns]

In [205]:
#len([1,2,3])
#len('123')
#len({'a':1,'b':2,'c':3})
#len(data)

# [1,2,3].size # AttributeError 
#'123'.size # AttributeError   
#{'a':1,'b':2,'c':3}.size # AttributeError   

import numpy as np
np.array([1,2,3]).size
data.size  # 244 * 7. DataFrame은 행과 열의 곱으로 반환한다.
data['tip'].size # Series도 size가 가능하다.
data.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [211]:
# 컬럼명을 바꿀 때 mapper, columns 옵션을 이용해서 변경할 수 있다.
data2 = data.rename(mapper={'size':'size_'},axis=1)
data2 = data.rename(columns={'size':'size_'})
data2

total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]